export const PRODUCT_CATEGORY_GROCERIES = 'groceries';
export const DISCOUNT_TYPE_EMPLOYEE = 0.3;
export const DISCOUNT_TYPE_AFFILIATE = 0.1;
export const DISCOUNT_TYPE_LOYALTY = 0.05;
export const DISCOUNT_TYPE_DEFAULT = 0;
export const DISCOUNT_AMOUNT = 5;
export const DISCOUNT_BILL_AMOUNT = 100;
export const YEARS_OF_LOYALTY = 2;

module.exports = {
  PRODUCT_CATEGORY_GROCERIES,
  DISCOUNT_TYPE_EMPLOYEE,
  DISCOUNT_TYPE_AFFILIATE,
	DISCOUNT_TYPE_LOYALTY,
	DISCOUNT_TYPE_DEFAULT,
  DISCOUNT_AMOUNT,
  DISCOUNT_BILL_AMOUNT,
  YEARS_OF_LOYALTY
};
